# Gopkg.toml for k8s.io/test-infra

# Updating this list likely also requires updating hack/prune-libraries.sh.
required = [
  "github.com/bazelbuild/bazel-gazelle/cmd/gazelle",
  "github.com/client9/misspell/cmd/misspell",
  "github.com/golang/dep/cmd/dep",
  "github.com/kubernetes/repo-infra/kazel",
]

[prune]
  unused-packages = true
  go-tests = true
  non-go = true

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.10"

[[constraint]]
  name = "k8s.io/apiserver"
  branch = "release-1.10"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.10"

[[constraint]]
  name = "k8s.io/client-go"
  version = "v7.0.0"

[[constraint]]
  name = "github.com/docker/docker"
  # https://github.com/docker/docker-ce/blob/17.12/components/cli/vendor.conf
  # to update this check https://github.com/docker/docker-ce/blob/<tag>/components/cli/vendor.conf 
  revision = "5e5fadb3c0201553929d4a6ea8dc8f9d8a1e56fe"

[[constraint]]
  name = "github.com/golang/dep"
  version = "v0.4.1"

[[constraint]]
  name = "cloud.google.com/go"
  version = "0.17.0"

[[constraint]]
  # used by both prow/plugins/buildifier and gazelle
  name = "github.com/bazelbuild/buildtools"
  revision = "80c7f0d45d7e40fa1f7362852697d4a03df557b3"

[[constraint]]
  name = "github.com/client9/misspell"
  revision = "9ce5d979ffdaca6385988d7ad1079a33ec942d20"

[[constraint]]
  name = "github.com/peterbourgon/diskv"
  revision= "2973218375c3d13162e1d3afe1708aaee318ef3f"

[[constraint]]
  name = "github.com/bazelbuild/bazel-gazelle"
  version = "0.11.0"
